export const BOOK_LIST = [
  { name: "Génesis", normalized: "genesis" },
  { name: "Éxodo", normalized: "exodo" },
  { name: "Levítico", normalized: "levitico" },
  { name: "Números", normalized: "numeros" },
  { name: "Deuteronomio", normalized: "deuteronomio" },
  { name: "Josué", normalized: "josue" },
  { name: "Jueces", normalized: "jueces" },
  { name: "Rut", normalized: "rut" },
  { name: "1 Samuel", normalized: "1 samuel" },
  { name: "2 Samuel", normalized: "2 samuel" },
  { name: "1 Reyes", normalized: "1 reyes" },
  { name: "2 Reyes", normalized: "2 reyes" },
  { name: "1 Crónicas", normalized: "1 cronicas" },
  { name: "2 Crónicas", normalized: "2 cronicas" },
  { name: "Esdras", normalized: "esdras" },
  { name: "Nehemías", normalized: "nehemias" },
  { name: "Ester", normalized: "ester" },
  { name: "Job", normalized: "job" },
  { name: "Salmos", normalized: "salmos" },
  { name: "Proverbios", normalized: "proverbios" },
  { name: "Eclesiastés", normalized: "eclesiastes" },
  { name: "Cantares", normalized: "cantares" },
  { name: "Isaías", normalized: "isaias" },
  { name: "Jeremías", normalized: "jeremias" },
  { name: "Lamentaciones", normalized: "lamentaciones" },
  { name: "Ezequiel", normalized: "ezequiel" },
  { name: "Daniel", normalized: "daniel" },
  { name: "Oseas", normalized: "oseas" },
  { name: "Joel", normalized: "joel" },
  { name: "Amós", normalized: "amos" },
  { name: "Abdías", normalized: "abdias" },
  { name: "Jonás", normalized: "jonas" },
  { name: "Miqueas", normalized: "miqueas" },
  { name: "Nahúm", normalized: "nahum" },
  { name: "Habacuc", normalized: "habacuc" },
  { name: "Sofonías", normalized: "sofonias" },
  { name: "Hageo", normalized: "hageo" },
  { name: "Zacarías", normalized: "zacarias" },
  { name: "Malaquías", normalized: "malaquias" },

  { name: "Mateo", normalized: "mateo" },
  { name: "Marcos", normalized: "marcos" },
  { name: "Lucas", normalized: "lucas" },
  { name: "Juan", normalized: "juan" },
  { name: "Hechos", normalized: "hechos" },
  { name: "Romanos", normalized: "romanos" },
  { name: "1 Corintios", normalized: "1 corintios" },
  { name: "2 Corintios", normalized: "2 corintios" },
  { name: "Gálatas", normalized: "galatas" },
  { name: "Efesios", normalized: "efesios" },
  { name: "Filipenses", normalized: "filipenses" },
  { name: "Colosenses", normalized: "colosenses" },
  { name: "1 Tesalonicenses", normalized: "1 tesalonicenses" },
  { name: "2 Tesalonicenses", normalized: "2 tesalonicenses" },
  { name: "1 Timoteo", normalized: "1 timoteo" },
  { name: "2 Timoteo", normalized: "2 timoteo" },
  { name: "Tito", normalized: "tito" },
  { name: "Filemón", normalized: "filemon" },
  { name: "Hebreos", normalized: "hebreos" },
  { name: "Santiago", normalized: "santiago" },
  { name: "1 Pedro", normalized: "1 pedro" },
  { name: "2 Pedro", normalized: "2 pedro" },
  { name: "1 Juan", normalized: "1 juan" },
  { name: "2 Juan", normalized: "2 juan" },
  { name: "3 Juan", normalized: "3 juan" },
  { name: "Judas", normalized: "judas" },
  { name: "Apocalipsis", normalized: "apocalipsis" }
];
